name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Create Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to docker repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0

      - name: Create build context
        run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: Set up TT environment
        run: |
          safe_ref=$(echo ${{ github.ref_name }} | sed -E 's/[^a-zA-Z0-9_.]+/-/g')
          (
          echo safe_ref=${safe_ref}
          echo docker_repo=ghcr.io/ttab/${{ github.repository }}
          echo docker_image=ghcr.io/ttab/${{ github.repository }}:${safe_ref}
          ) >> $GITHUB_ENV

      - name: Build and push release image
        uses: docker/build-push-action@v3
        with:
          context: .
          # Specify the build_platforms variable in the GitHub repo
          platforms: ${{ vars.BUILD_PLATFORMS }}
          push: true
          build-args: |
            COMMAND=repository
          tags: ${{ env.docker_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
