name: Run tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read
  statuses: write

jobs:
  tests:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.2'
          cache: true
      - uses: ouzi-dev/commit-status-updater@v2
        with:
          name: tests
      - name: Run tests
        run: |
          go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
      - if: always()
        uses: ouzi-dev/commit-status-updater@v2
        with:
          name: tests
          status: "${{ job.status }}"
